# Generated by Django 5.2 on 2026-09-20 22:36

import core.utils
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корзина покупок',
                'verbose_name_plural': 'Корзины покупок',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество позиций')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Сумма')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('cancelled', 'Отменен'), ('pending', 'В ожидании'), ('completed', 'Завершен')], default='pending', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9]{8}')], verbose_name='Public ID позиции')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='Наименование в заказе')),
                ('item_quantity', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество позиций')),
                ('item_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Цена в заказе')),
                ('item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Сумма позиции')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Цена')),
                ('warehouse_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
    ]
