class TestCartConstants:
    CART_INVALID_COUNT_ITEM = -1
    CART_ITEM_ONE = 1
    CART_ITEM_THREE = 3
    CART_ITEM_TWO = 2
    CART_ITEM_ELEVEN = 11
    CART_NO_ITEM = 0


class TestProductConstants:
    FIRST_PRODUCT_IDX = 0
    PRODUCT_ONE = 1
    PRODUCT_TWO = 2
    WAREHOUSE_QUANTITY_ONE = 1
    WAREHOUSE_QUANTITY_TEN = 10
    WAREHOUSE_QUANTITY_TWENTY = 20
